---
- name: create certificate authority directories on CA
  delegate_to: "{{ nebula_ca }}"
  file:
    path: "{{ nebula_ca_dir }}"
    state: directory

- name: create the organization certificate authority
  delegate_to: "{{ nebula_ca }}"
  command: 'nebula-cert ca -out-qr ' + nebula_ca_dir + '/ca.crt.jpg -name "{{ nebula_ca_name }}"'
  run_once: true
  args:
    chdir: "{{ nebula_ca_dir }}"
    creates:
      - "{{ nebula_ca_dir }}/ca.crt"
      - "{{ nebula_ca_dir }}/ca.crt.jpg"

- name: sign certificates for nebula nodes
  delegate_to: "{{ nebula_ca }}"
  command: "{{ 'nebula-cert sign -out-qr ' + nebula_ca_dir + '/' + nebula_hostname + '.crt.jpg -name ' + nebula_hostname + ' -ip ' + nebula_ip + nebula_cidr + ' -groups ' + nebula_groups }}"
  args:
    chdir: "{{ nebula_ca_dir }}"
    creates:
      - "{{ nebula_ca_dir }}/{{ nebula_hostname }}.crt"
      - "{{ nebula_ca_dir }}/{{ nebula_hostname }}.crt.jpg"
      - "{{ nebula_ca_dir }}/{{ nebula_hostname }}.key"

- name: sign certificates for nebula client devices
  delegate_to: "{{ nebula_ca }}"
  command: "{{ 'nebula-cert sign -out-qr ' + nebula_ca_dir + '/' + item.nebula_hostname + '.crt.jpg -name ' + item.nebula_hostname + ' -ip ' + item.nebula_ip + nebula_cidr + ' -groups ' + item.nebula_groups }}"
  args:
    chdir: "{{ nebula_ca_dir }}"
    creates:
      - "{{ nebula_ca_dir }}/{{ item.nebula_hostname }}.crt"
      - "{{ nebula_ca_dir }}/{{ item.nebula_hostname }}.crt.jpg"
      - "{{ nebula_ca_dir }}/{{ item.nebula_hostname }}.key"
  run_once: true
  loop: "{{ nebula_client_devices }}"
