---
#TODO: Support porvision of multiple CA files

- name: create certificate authority directories on CA
  delegate_to: "{{ nebula_ca }}"
  file:
    path: "{{ nebula_ca_dir }}"
    state: directory

- name: Create the organization certificate authority
  delegate_to: '{{ nebula_ca }}'
  command: 'nebula-cert ca -name "{{ nebula_ca_name }}"'
  run_once: true
  args:
    chdir: "{{ nebula_ca_dir }}"
    creates: "{{ nebula_ca_dir }}/ca.crt"

